export { default as HomePage } from './HomePage'
export { default as QuizPage } from './QuizPage'
export { default as ResultPage } from './ResultPage'
export { default as CheckNotePage } from './CheckNotePage'
export { default as NotFoundPage } from './NotFoundPage'
